engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      exclude_paths:
      - "**.spec.js"
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
